### ISSUE TITLE
API doesn't have a function to return auth-url for specific provider

### ISSUE THREAD

**Issue by kaosko** [blmstrm/loudmoauth#5]
The core api seems to have an interesting design decision just to return the first provider that doesn't hold access token. Is there are reason for it? I would have thought users typically want to interact with a specific provider, i.e. perhaps (defn user-interaction ....) should provide multi-arity function to accept provider as a parameter for
`(:auth-url (lma-p/provider-reverse-lookup provider @lma/providers))`.

**Comment by blmstrm** [comment]
Hi Kaosko!
Thanks for posting and sorry for the late reply. Your specific use case hadn't occurred to me as I always thought of the ````user-interaction```` part of the auth flow as a step you would do once for all of your providers and then forget about it. But I can see how someone would like to authenticate with one specific provider among the defined ones, so if you have a PR I'll be glad to take it.
